TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Configuration data files are installed in $TOP)/data
#DATA += xxx.pv
DATA += axisLimits.par
DATA += cwpos1CP.par
DATA += cwpos1MK.par
DATA += cwpos1.par
DATA += cwpos2CP.par
DATA += cwpos2MK.par
DATA += cwpos2.par
DATA += cwpos3CP.par
DATA += cwpos3MK.par
DATA += cwpos3.par
DATA += logDataCP.par
DATA += logDataMK.par
DATA += logData.par
DATA += sony.par
DATA += stageCP.par
DATA += stageMK.par
DATA += stage.par
DATA += tapePolys.par
DATA += telescope.par
DATA += test.par

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

